name: angular_flatpickr
description: AngularDart port of flatpickr (javascript date/time picker).
version: 0.0.2
homepage: https://github.com/alexd1971/angular_flatpickr
author: Aleksey Danilevskiy <alexey.danilevsky@gmail.com>

environment:
  sdk: '>=2.3.0 <3.0.0'

dependencies:
  angular: ^6.0.0-alpha
  angular_forms: ^2.1.3
  js: '>=0.6.1 <0.7.0'

dev_dependencies:
  angular_test:
  pageloader:
  test:

transformers:
  - angular:
      entry_points:
        - test/**_test.dart
  - test/pub_serve:
      $include: test/**_test.dart